name: tedbook
description: "book delivery"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  dio: ^5.5.0
  flutter_svg: ^2.0.6
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  buttons_tabbar: ^1.3.13
  jwt_decoder: ^2.0.1
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  logger: ^2.4.0
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.3.1
  flutter_styled_toast: ^2.2.1
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
