export const TOKEN = 'TEDBOOK_APP_TOKEN';
export const REFRESH_TOKEN = 'TEDBOOK_APP_REFRESH_TOKEN';
export const TOKEN_CREATED_AT = 'TEDBOOK_APP_TOKEN_CREATED_AT';
export const TOKEN_EXPIRES_AT = 'TEDBOOK_APP_TOKEN_EXPIRES_AT';
